server:
  servlet:
    port: 8080
    context-path: /api

spring:
  application:
    name: Covid Helper
  data:
    mongodb:
      uri: mongodb://localhost:27017/covidhelper
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 722607456520-p2kg7jk1m8gbetqhq856h89t1ug19fn9.apps.googleusercontent.com
            clientSecret: 5QL6IBR4KNqxk5zDcsgLSjTp
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 589441458357676
            clientSecret: 48e0a723e5dcf9cf9b3597c89e7b7aab
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

